#16 Move Profile in to esn-frontend-account
OpenPaaS-Suite/esn-frontend-account pull request #37
Opened 2020-08-24 12:37 UTC by fabienmoyon

## Desktop

![OpenPaas (1) (1)](https://user-images.githubusercontent.com/11298249/88390478-ac807e00-cdb8-11ea-8e16-1d8f6a21c091.gif)

## Mobile

![localhost_9900_(iPhone X) (1)](https://user-images.githubusercontent.com/11298249/88391180-f61d9880-cdb9-11ea-92d5-6679faa6ad9c.png)

![Peek 24-07-2020 16-24](https://user-images.githubusercontent.com/11298249/88401631-44d32e80-cdca-11ea-8f08-b02e4e431d30.gif)

2020-08-24 12:48 UTC, rezk2ll commented on src/linagora.esn.controlcenter/app/profile-menu-controlcenter/profile-menu-controlcenter.pug
> +    | {{ 'Account' | translate }}
```suggestion
    | {{ 'Account' | translate }}

```

2020-08-24 12:48 UTC, rezk2ll commented on src/linagora.esn.profile/app/sidebar/sidebar-menu-item.component.js
> +(function(angular) {
IIFE are no longer needed i guess

2020-08-24 12:48 UTC, rezk2ll commented on src/linagora.esn.profile/app/sidebar/sidebar.less
> +}
```suggestion
}

```

2020-08-24 14:46 UTC, asmaNode approved these changes

2020-08-24 15:05 UTC, asmaNode approved these changes

2020-08-25 01:01 UTC, tuanlc commented
From your demo on desktop, when you choose `profil` item in the sidebar, it is not highlighted (Darker) like when you choose `Parametre`. Do you see it?

2020-08-25 01:07 UTC, tuanlc requested changes

2020-08-25 01:07 UTC, tuanlc commented on src/linagora.esn.profile/app/sidebar/sidebar-menu-item.component.js
> +
remove this blank line

2020-08-25 01:07 UTC, tuanlc commented on src/linagora.esn.profile/app/sidebar/sidebar.component.js
> +(function(angular) {
No need IIFE anymore

2020-08-25 01:07 UTC, tuanlc commented on src/linagora.esn.profile/app/sidebar/sidebar-menu-item.pug
> +  .menu-title {{::$ctrl.label | esnI18n}}
Does it work? Should be:

```suggestion
  .menu-title {{::$ctrl.label | translate}}
```

2020-08-25 02:28 UTC, huy-ta commented on src/linagora.esn.profile/app/app.less
> +     img {
Wrong indentation.

2020-08-25 02:28 UTC, huy-ta commented on src/linagora.esn.controlcenter/app/profile-menu-controlcenter/profile-menu-controlcenter.pug
> +    | {{ 'Account' | translate }}
Please add a blank line at the end of the file here.

2020-08-25 13:46 UTC, fabienmoyon commented
> From your demo on desktop, when you choose `profil` item in the sidebar, it is not highlighted (Darker) like when you choose `Parametre`. Do you see it?

Yes it's fixed ;)

2020-08-25 14:58 UTC, chamerling approved these changes

2020-08-25 15:25 UTC, merged