#20 Add sidebar and burger menu in to esn-frontend-account
OpenPaaS-Suite/esn-frontend-account pull request #38
Opened 2020-08-24 12:40 UTC by fabienmoyon

**NEED https://github.com/OpenPaaS-Suite/esn-frontend-account/pull/37 BEFORE** 

## Desktop

![OpenPaas (1) (1)](https://user-images.githubusercontent.com/11298249/88390478-ac807e00-cdb8-11ea-8e16-1d8f6a21c091.gif)

## Mobile

![localhost_9900_(iPhone X) (1)](https://user-images.githubusercontent.com/11298249/88391180-f61d9880-cdb9-11ea-92d5-6679faa6ad9c.png)

![Peek 24-07-2020 16-24](https://user-images.githubusercontent.com/11298249/88401631-44d32e80-cdca-11ea-8f08-b02e4e431d30.gif)

2020-08-24 14:50 UTC, asmaNode commented on src/linagora.esn.controlcenter/app/app.run.js
> +  };
missing blank line

2020-08-24 14:50 UTC, asmaNode commented on src/linagora.esn.profile/app/sidebar/sidebar.less
> +}
some here

2020-08-25 01:12 UTC, tuanlc requested changes

2020-08-25 01:12 UTC, tuanlc commented on src/linagora.esn.controlcenter/app/app.run.js
> +  }).run(fillTemplates);
Break the new run block to a new line

```suggestion
  })
  .run(cacheTemplates);
```

2020-08-25 01:12 UTC, tuanlc commented on src/linagora.esn.profile/app/app.less
> +  height: auto;
Useless blank line before and missing blank line after

2020-08-25 01:12 UTC, tuanlc commented on src/linagora.esn.profile/app/app.run.js
> +  }).run(fillTemplates);
```suggestion
  })
  .run(cacheTemplates);
```

2020-08-25 01:12 UTC, tuanlc commented on src/linagora.esn.profile/app/sidebar/sidebar-menu-item.component.js
> +(function(angular) {
No need IIFE anymore

2020-08-25 01:12 UTC, tuanlc commented on src/linagora.esn.profile/app/sidebar/sidebar-menu-item.pug
> +  .menu-title {{::$ctrl.label | esnI18n}}
Does it work? It should be:

```suggestion
  .menu-title {{::$ctrl.label | translate}}
```

2020-08-25 01:12 UTC, tuanlc commented on src/linagora.esn.profile/app/sidebar/sidebar.component.js
> +(function(angular) {
Remove IIFE

2020-08-25 16:02 UTC, asmaNode approved these changes

2020-08-25 19:40 UTC, rezk2ll approved these changes

2020-08-26 01:12 UTC, tuanlc approved these changes

2020-08-27 08:39 UTC, merged